config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  get '/register', to: 'users#new', as: "register"

  post '/users', to: 'users#create'

  get '/users/:id', to: 'users#show', as: "user"

  get 'users/:id/edit', to: 'users#edit', as: "edit_user"

  patch 'users/:id', to: 'users#update'

  get '/users/:id/survey', to: 'users#survey', as: "new_survey"

  get '/login', to: "sessions#new", as: "login"
  post '/sessions', to: "sessions#create"
  delete "/logout", to: "sessions#delete", as: "logout"

  get '/pets', to: "pets#index", as: "pets"

  get '/pets/:id', to: 'pets#show', as: "pet"

  get '/preferences/users/:id', to: 'preferences#survey'

  post '/preferences', to: 'preferences#create'

  get '/preferences/users/:id/edit', to: 'preferences#edit', as: "edit_preferences"

  patch '/preferences/users/:id', to: 'preferences#update', as: "preference"

  get '/users/:id/matches', to: 'users#matches', as: "matches"

  post 'users/:id/matches', to: 'users#refresh_pets'

  get '/about', to: 'welcome#about'

  get '/contact', to: 'welcome#contact'

  post '/user_pets/:id', to: 'user_pets#create'

  post '/user_pets/delete/:id', to: 'user_pets#delete'


#   Prefix Verb   URI Pattern          Controller#Action
#     root GET    /                    welcome#index
# new_user GET    /users/new(.:format) users#new
#    users POST   /users(.:format)     users#create
#     user GET    /users/:id(.:format) users#show
#    login GET    /login(.:format)     sessions#new
#          POST   /login(.:format)     sessions#create
#   logout DELETE /logout(.:format)    sessions#delete

end

app/models/user.rb
class User < ActiveRecord::Base
	validates_uniqueness_of :email

	has_many :user_pets
	has_many :pets, :through => :user_pets

	has_secure_password

	validates :password, presence: true,
	length: {:minimum => 5},
	length: {:maximum => 20}

	validates :first_name, presence: true, length: { maximum: 20 }

	validates :last_name, presence: true, length: { maximum: 25 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

	serialize :survey_info
	def self.confirm (params)
		@user = User.find_by({email: params[:email]})
		@user.try(:authenticate, params[:password])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
		@user = User.new
	end

	def create
		# changed User.create
		@user = User.create(user_params)

		login(@user)
		if @user != nil
			redirect_to "/preferences/users/#{@user.id}"
		else
			flash[:notice] = "There was an error: " + @user.errors
			#flash[:notice] = @user.errors.full_messages.to_sentence
			redirect_to root_path
		end

		# if @user.save
		# 	# login user
		# 	login(@user)
		# 	# redirect to set up 'cat_or_dog' or will throw an error
		# 	redirect_to "/preferences/users/#{@user.id}"

		# else
		# 	flash[:nosignup] = "All fields are required"
		# 	#flash[:notice] = @user.errors.full_messages.to_sentence
		# 	redirect_to root_path

		# end
	end

	def survey
		@user = User.find(params[:id])
		render :survey
	end

	def show
		@user = User.find(params[:id])
		render :show

	end

	def edit
		@user = User.find(params[:id])

		render :edit
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to user_path(@user)
	end

	def matches
		@user = current_user
		if @user.id != params[:id].to_i
			redirect_to "/users/#{@user.id}"
			return
		end

		@pets = Pet.all
			.where(species: cat_or_dog)
			.where(activity_level: activity_level)
			.where("age > ?", age_cutoff)
			.where("weight < ?", size_of_home)
			.where("age > ?", time_with_pet)
		@user = User.find(params[:id])	

		render :matches
	end


	def refresh_pets
		Pet.delete_all
		#PG::ForeignKeyViolation: ERROR:  update or delete on table "pets" violates foreign key constraint "fk_rails_dedd5edecd" on table "user_pets
		@user = current_user
		# added () after get
		response_cats = HTTParty.get('https://www.kimonolabs.com/api/bo1g4i5q?apikey=0AQUI7VQU8WOOshS9WxdFpe02TiuGorc')

		response_cats["results"]["collection1"].each do |cat|
			# if status is 200
			Pet.create({name: cat["name"], species: "cat", gender: cat["gender"], age: convert_age_to_months(cat["age"]),
					 weight: convert_weight_to_ounces(cat["weight"]), description: cat["description"],
					 thumbnail: cat["picture"]["src"], shelter_id: cat["id"], personality: cat_personality(cat["personality"])})

			end

		response_dogs = HTTParty.get('https://www.kimonolabs.com/api/ch62ea86?apikey=0AQUI7VQU8WOOshS9WxdFpe02TiuGorc')

		response_dogs["results"]["collection1"].each do |dog|
			# if status is 200
			Pet.create({name: dog["name"], species: "dog", gender: dog["gender"], age: convert_age_to_months(dog["age"]),
					 weight: convert_weight_to_ounces(dog["weight"]), description: dog["description"], thumbnail: dog["picture"]["src"],
					 personality: dog_personality(dog["personality"]), activity_level: dog["activity_level"], shelter_id: dog["id"]})
			end


		redirect_to matches_path(@user.id)
	end

	private
		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :password, :photo_url, :survey_info)
		end

		def cat_or_dog
			# should determine which set of data to sort through
			# TODO: need to add preferences to the user
			@user_preferences = Preference.find_by({user_id: current_user.id})
			return @user_preferences.cat_or_dog
		end

		def activity_level
			if cat_or_dog == "dog"
				return @user_preferences.activity_level
			elsif cat_or_dog == "cat"
				return nil
			end
		end

		def age_cutoff
			# do not return pets younger than 5 months
			if young_children || training_pet
				5
			else
				0
			end
		end

		def young_children
			@user_preferences.young_children == "yes"
		end

		def size_of_home

			if @user_preferences.size_of_home == "1" || @user_preferences.size_of_home == "small apartment"
				# return small to medium dogs
				return 880
			elsif @user_preferences.size_of_home == "2" || @user_preferences.size_of_home == "big apartment"
				# return all but the largest dogs
				return 1600
			elsif @user_preferences.size_of_home == "3" || @user_preferences.size_of_home == "house"
				# return all dogs
				return 3200
			end
		end

		def time_with_pet
			if cat_or_dog == "dog"
				if @user_preferences.time_with_pet == "not a lot"
					# return adult dogs or maybe cats
					return 24
				elsif @user_preferences.time_with_pet == "decent amount"
					# return all dogs that are not puppies and cats
					return 12
				elsif @user_preferences.time_with_pet == "lots of time"
					# return all pets
					return 0
				end
			end
			return 0
		end

		def training_pet
			@user_preferences.training_pet == "no"
		end



		def convert_age_to_months(age_string)
			parse_string_to_number(age_string, 12)
		end

		def convert_weight_to_ounces(weight_string)
			parse_string_to_number(weight_string, 16)
		end

		# string is something like "3Y 2M" for age or "5lbs. 6oz." for weight
		# multiplier is 12 for age and 16 for weight.

		def parse_string_to_number(string, age_or_weight)


			multiplier = age_or_weight == 'age' ? 12 : 16
				return nil if string.nil?
				num_string = string.gsub(/[^0-9]/, ' ')
				# num_array is an array of the component numbers making up the string
				num_array = num_string.split(' ').map { |s| s.to_i }	
				if num_array.length == 1
					# if only one digit is provided, it's a number of months for age, or a number of pounds for 
					# weight, so we only multiply for weight
					if age_or_weight == 'age'
						return num_array[0]
					else 
						return num_array[0] * multiplier
					end
				else 
					return num_array[0] * multiplier + num_array[1]
				end 
		end

		def user_personality
			if cat_or_dog == "cat"
				if @user_preferences.user_personality == "I'm very active"
					return "Poet"
				elsif @user_preferences.user_personality == "I prefer quiet places"
					return "Lion hearted"
				end
			else
				return "busy bee"
			end
		end

		def dog_personality(data)
			if data == nil
				return "zen master"
			end
			return data
		end

		def cat_personality(data)
			if data == nil
				return "Cat Next Door"
			end
			return data
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_prefs_modal.html.erb
<!-- Modal -->
<div id="edit_prefs_Modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

<!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Change Pet Preferences</h4>
      </div>
      <div class="modal-body">

		<%= form_for @preference do |f|%>
			<p>What is your prefered animal?</p>
			<%= f.select :cat_or_dog, options_for_select([['cat'], ['dog']]) %>

			<p>What is your activity level?</p>
			<%= f.select :activity_level, options_for_select([['High'], ['Medium'], ["Low"]]) %>

			<!-- need hidded field that contains @user.id -->
			<p> Do you have young children(less than 5 years old)?</p>
			<%= f.select :young_children, options_for_select([['yes', 1], ['no', 2]]) %>

			<p>How big is your home? One bedroom or studio(not a lot of space)</p>
			<%= f.select :size_of_home, options_for_select([['small apartment', 1], ['big apartment', 2], ["house", 3]]) %>

			<p> How much time would you be able to spend with your pet each day? </p>
			<%= f.select :time_with_pet, options_for_select([['not a lot'], ['decent amount'], ["lots of time"]]) %>

			<p> Are you willing to spend a lot of time training a pet?</p>
			<%= f.select :training_pet, options_for_select([['yes'], ['no']]) %>
			<div style="display: none">
				<%= f.text_field :user_id, value: "#{@user.id}" %>
			</div> <br>
			<br>
			<%= f.submit "Submit",  class: "btn btn-primary"%>
		<% end %>

 	  </div><!-- end modal body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/users/_edit_user_modal.html.erb
<!-- Modal -->
<div id="edit_user_Modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

<!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit Profile</h4>
      </div>
      <div class="modal-body">

      	<%= bootstrap_form_for @user do |f| %>
      	<div>
      	<%= f.text_field :first_name, placeholder: 'First Name' %>
      	</div>
      		<div>
      			<%= f.text_field :last_name, placeholder: 'Last Name' %>
      		</div>
      		<div>
      			<%= f.email_field :email, placeholder: 'Email (username)' %>
      		</div>
      		<div>
      		<%= f.text_field :photo_url, placeholder: "Profile Image URL" %>
      		</div>
      		<hr>
      		<h4>Reset Password</h4>
      		<div>
      			<%= f.password_field :password, placeholder: 'Password' %>
      		</div>
      		<div>
      			<%= f.submit "Save Changes" %>
      		</div>
      	<% end %>

      	    <div class="form-group">
      	      <%= link_to "Cancel", "javascript:history.go(-1);", class: "col-sm-1" %></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/users/edit.html.erb
<hr>
<div class="jumbotron">
<h1>Edit Profile</h1></div>
<hr>

<% if @user == current_user %>
<%= render 'users/edit_user_modal'%>
<% end %>

app/views/users/matches.html.erb
<div class="row">
	<div class="col-md-9">
		<h1>Hey <%=@user.first_name.capitalize%>! Here are the available pets in your area:</h1>
	</div>
	<div class="col-md-2 col-md-offset-1">
		<%= button_to "Refresh pets", matches_path, class: "refresh-button btn btn btn-success" %>
		<button type="button" class="btn btn-info" data-toggle="modal" data-target="#edit_prefs_Modal" style="margin: 10px 0 0 15px;">Edit Preferences</button>
	</div>
</div>

<div class="row" style="margin-top: 80px;">
	<div class="col-md-12">
	<% @pets.each do |pet| %>
		<% if pet.thumbnail == nil %>
			<div style="display: none;"><%= pet.species %></div>
		
		<% else %>

			<div class="col-md-3 text-center matchesDiv">
				<%= link_to image_tag(pet.thumbnail), pet_path(pet.id), class: "img img-thumbnail" %>
				<p><%= pet.name %> </p>
				<% if UserPet.all.where(user_id: @user.id).where(pet_id: pet.id) == [] %>
					<%= link_to "Add to Favorites", "/user_pets/#{pet.id}", method: :post, class: "fave-button btn btn-success" %> 
				<% end %>
			</div>
		
		<% end %>
	<% end %>

	</div>
</div>
<%= render 'users/edit_prefs_modal'%> 

app/views/users/new.html.erb
<div>
<%=form_for @user do |f| %>
	<%= f.text_field :first_name, placeholder: "first name" %> <br>
	<%= f.text_field :last_name , placeholder: "last name" %> <br>
	<%= f.email_field :email, placeholder: "email" %> <br>
	<%= f.password_field :password, placeholder: "password" %><br>
	<%= f.text_field :photo_url, placeholder: "Profile Image URL" %><br>
	<%= f.submit "sign up"%>
<% end %>
</div>

app/views/users/show.html.erb
<%= image_tag(@user.photo_url)%>


<% if current_user == @user %>

<div class="row">
	<div class="col-md-12 well" style="background: transparent;">
		<div class="col-md-4">
			<h3>Hello, <%= @user.first_name.capitalize %></h3>
		</div>
		<div class="col-md-8">
			<div class="row">
				<h4>Your settings:</h4>
				<div class="col-md-3"><%= link_to "View your matches!", "/users/#{@user.id}/matches", class: "btn btn-success" %></div>
				<div class="col-md-3"><button type="button" class="btn btn-info" data-toggle="modal" data-target="#edit_prefs_Modal">Edit Preferences</button>
				</div>
				<div class="col-md-3">
					<%= button_to "Logout", logout_path, class: "btn btn-primary", method: :delete %>
				</div>
			</div>
		</div>
	</div>
</div>
<% else %>
	<div class="jumbotron">
	<h3><%= @user.first_name.capitalize %>'s page</h3></div>
<% end %>

<%= render 'users/edit_prefs_modal'%> 

<% if current_user == @user %>
	<div class="row" style="margin-top: 80px;">
	<h3>Here are your favorite pets from your pet match:</h3>
		<div class="col-md-12 well" style="background: transparent;">
		
		<% @user.pets.each do |pet|%>
			<% if pet.thumbnail == nil %>
				<div style="display: none;"><%= pet.species %></div>
			
			<% else %>
				<div class="col-md-3 text-center">
					<%= link_to image_tag(pet.thumbnail), pet_path(pet.id), class: "img img-thumbnail" %>
					<p><%= link_to pet.name, pet.link %> </p>
					<%= button_to "Remove from favorites", "/user_pets/delete/#{pet.id}", class: "btn btn-danger" %> 
				</div>
			
			<% end %>
		<% end %>
		</div>
	</div>
<!-- non-modal edit prefs -->

<!-- modalized -->
	
<%end%>




<!-- logout button -->

app/views/users/survey.html.erb
<!-- need model and controller for preferences. -->
<!-- the preferences will "belong_to" a user -->
<!-- the controller will handle the creation and edit/updating preferences as well as the logic for  -->
<!-- determinging which results are shown -->
<%= form_for @preference do |f|%>
	<p>What is your prefered animal? cat/dog</p>
	<%= f.select :cat_or_dog, options_for_select([['cat', 1], ['dog', 2]]) %>

	<p>What is your activity level? high(you love going on walks)/average/low (if low and they want a dog, suggest small dogs)</p>
	<%= f.select :activity_level, options_for_select([['high', 1], ['medium', 2], ["low", 3]]) %>

	<p> Do you have young children(less than 5 years old)? yes/no (if yes, don't suggest puppies or kittens ==> less than 5 months)
 </p>
	<%= f.select :young_children, options_for_select([['yes', 1], ['no', 2]]) %>

	<p>How big is your home? One bedroom or studio(not a lot of space)/2-3 bedroom(more space)/house(a lot of space) </p>
	<%= f.select :size_of_home, options_for_select([['small apartment', 1], ['big apartment', 2], ["house", 3]]) %>

	<p> How much time can you spend with the animal per day? not a lot/a resonable amount/I can bring my pet(dog) to work
 </p>
	<%= f.select :time_with_pet, options_for_select([['not a lot', 1], ['decent amount', 2], ["lots of time", 3]]) %>

	<p> Are you willing to spend a lot of time training a pet? yes/somewhat(will take pet to trainging school if dog)/no, it should come trained </p>
	<%= f.select :training_pet, options_for_select([['yes'], ['no']]) %>

	<p> Which of these best describes you? </p> 
	<!-- social butterfly+busybee+jock+peewee+zen master/zen master+country dog delicate flower -->
	<!-- cat next door + lionhearted/poet+cat next door -->
	<%= f.select :user_personality, options_for_select([["I'm very active"], ["I prefer quiet places"]]) %>

	<!-- need hidded field that contains @user.id -->
	<div style="display: none">
		<%= f.text_field :user_id, value: "#{@user.id}" %>
	</div>
	<br>
	<%= f.submit "Submit" class: "btn btn-default" %>
<% end %>