config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  get '/register', to: 'users#new', as: "register"

  post '/users', to: 'users#create'

  get '/users/:id', to: 'users#show', as: "user"

  get 'users/:id/edit', to: 'users#edit', as: "edit_user"

  patch 'users/:id', to: 'users#update'

  get '/users/:id/survey', to: 'users#survey', as: "new_survey"

  get '/login', to: "sessions#new", as: "login"
  post '/sessions', to: "sessions#create"
  delete "/logout", to: "sessions#delete", as: "logout"

  get '/pets', to: "pets#index", as: "pets"

  get '/pets/:id', to: 'pets#show', as: "pet"

  get '/preferences/users/:id', to: 'preferences#survey'

  post '/preferences', to: 'preferences#create'

  get '/preferences/users/:id/edit', to: 'preferences#edit', as: "edit_preferences"

  patch '/preferences/users/:id', to: 'preferences#update', as: "preference"

  get '/users/:id/matches', to: 'users#matches', as: "matches"

  post 'users/:id/matches', to: 'users#refresh_pets'

  get '/about', to: 'welcome#about'

  get '/contact', to: 'welcome#contact'

  post '/user_pets/:id', to: 'user_pets#create'

  post '/user_pets/delete/:id', to: 'user_pets#delete'


#   Prefix Verb   URI Pattern          Controller#Action
#     root GET    /                    welcome#index
# new_user GET    /users/new(.:format) users#new
#    users POST   /users(.:format)     users#create
#     user GET    /users/:id(.:format) users#show
#    login GET    /login(.:format)     sessions#new
#          POST   /login(.:format)     sessions#create
#   logout DELETE /logout(.:format)    sessions#delete

end

app/views/layouts/_footer.html.erb
  <div id="footer">
    <div class="row">
      <div class="col-sm-12">
        <div class="col-sm-3 col-sm-offset-3">
          <p><strong>About</strong></p>
          <p>Pet match is a non-profit organization dedicated to connecting caring humans looking for companionship with fabulous, furry and feathery friends.</p>
        </div>
        <div class="col-sm-3">
          <p><strong>Shelters and Rescues</strong></p>
          <p>Check out local resources to find your next pet match:</p>
          <p><a href="https://www.sfspca.org/" target="_blank">San Francisco SPCA</a></p>
          <p><a href="http://wondercatrescue.org/" target="_blank">Wonder Cat Rescue</a></p>
          <p><a href="http://www.rocketdogrescue.org/" target="_blank">Rocket Dog Rescue</a></p>
          <p><a href="http://www.mickaboo.org/" target="_blank">Mickaboo Companion Bird Rescue</a></p>
        </div>
        <div class="col-sm-3">
          <p><strong>Contact Us</strong></p>
          <p>415.512.1234</p>
          <p>info@pet-match.org</p>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_navbar2.html.erb
<nav class="navbar navbar-fixed-top">

<div class="top-top"><p class="small white">info@petmatch.com</p></div>
    <div class="container-fluid white-bck">
    <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <div class="navbar-logo" href="<%=root_path%>"><%= image_tag "pet_logo.jpg", width: "250px", height: "110px"%></div>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
         </button>
        </div>

        <!-- float this right -->
        <div class="navbar-right navbar-collapse margin-right" role="navigation" id="navbar-collapse-1">
        <ul>
          <li class="text-center nav-block" style="background-color: #51a7fa;"><span class="glyphicon glyphicon-home white icon-block"></span><a href="<%=root_path%>" class="white"> Home</a></li>

          <li class="text-center nav-block" style="background-color: #773e9c;"><span class="glyphicon glyphicon-log-in white icon-block"></span><a href="/about" class="white"> About</a></li>

          <!-- take me to my page -->
        <% if @user %>
          <li id="dropdownMenu1" data-toggle="dropdown" class="dropdown text-center nav-block" style="background-color: #70bf40;"><span class="glyphicon glyphicon-user white icon-block"></span><a href="#" data-toggle="dropdown" class="dropdown-toggle white"> Account</a> <span class="caret white"></span>

            <ul class="dropdown-menu green" aria-labelledby="dropdownMenu1">

              <li><a data-toggle="modal" data-target="#edit_user_Modal"><span class="glyphicon glyphicon-cog white"></span> Edit Profile</a></li>

              <li><a data-method="get" href="<%= user_path(@user) %>"><span class="glyphicon glyphicon-user white"></span> View Profile</a></li>

              <li><a data-method="get" href="<%= matches_path(@user) %>"><span class="glyphicon glyphicon-heart white"></span> Pet Matches</a></li>

              <li><a data-method="delete" href="<%= logout_path %>" class="white"><span class="glyphicon glyphicon-log-out white"></span> Logout</a></li>

            </ul>
          </li>

          <% end %>
          <% if @user == nil %>
          
            <li class="text-center nav-block" style="background-color: #70bf40;"><span class="glyphicon glyphicon-log-in white icon-block"></span><a data-target="#myModal" data-toggle="modal" class="white"> Login</a></li>

         <% end %>

             <li class="text-center nav-block" style="background-color: #dd6a0f;"><span class="glyphicon glyphicon-heart white icon-block"></span><a href="/pets" class="white"> Pets </a></li>
             
             <li class="text-center nav-block" style="background-color: #f8d905;"><span class="glyphicon glyphicon-envelope white icon-block"></span><a href="/contact" class="white"> Contact</a></li>
         </ul>
        </div>

  </div>
</nav>

app/views/layouts/_welcome_modal.html.erb
<!-- Modal -->
<div aria-hidden="true" aria-labelledby="myModalLabel" class="modal fade" id="myModal" role="dialog" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Register</h4>
      </div>
      <div class="modal-body">
        <div id="signDiv" style="display: block;">

          <%= bootstrap_form_for :user, url: "/users", method: "post" do |f| %>
          <div class="form-group has-error">
            <%= f.text_field :first_name, class: "form-control", placeholder: "First Name", help: "Required field" %>
          </div>
          <div class="form-group has-error">
            <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name", help: "Required field" %>
          </div>
          <div class="form-group has-error">
            <%= f.email_field :email, class: "form-control", placeholder: "Email", help: "Required field" %>
          </div>
          <div class="form-group has-error">
            <%= f.password_field :password, class: "form-control", placeholder: "Password", help: "Required field" %>
          </div>
          <div class="form-group">
            <%= f.submit "Register", class: "btn btn-success" %>
            <button aria-pressed="false" autocomplete="off" class="btn btn-primary pull-right" data-toggle="button" id="formToggle" onclick="petmatch.memberSignIn()" type="button">Returning? Sign In</button>
          </div>
          <% end %>

        </div>
        <div id="logDiv" style="display: none;">

          <%= bootstrap_form_for :user, url: "/sessions", method: "post" do |f| %>

          <div class="form-group has-error">
            
            <%= f.text_field :email, class: "form-control", placeholder: "Email", help: "Required field" %>
          </div>
          <div class="form-group has-error">
            
            <%= f.password_field :password, class: "form-control", placeholder: "Password", help: "Required field" %>
          </div>
          <div class="form-group">
            <%= f.submit "Sign In", class: "btn btn-success" %>
            <button aria-pressed="false" autocomplete="off" class="btn btn-primary pull-right" data-toggle="button" id="formToggle2" onclick="petmatch.memberRegister()" type="button">New? Register Now</button>
          </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pet-Match</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body>
<div id="wrapper">
<%= render partial: "layouts/navbar2", locals: {user: @user} %>

  <div class="container">
    <%= yield %>
  </div>
  

  <!-- modal -->
  <% if @user %>
  <%= render 'users/edit_user_modal', locals: {user: @user, preference: @preference} %>
  <% end %>

<%= render 'layouts/welcome_modal'%>
<h1> <%= flash[:notice] %></h1>
<%= render partial: "layouts/footer" %>
</div><!-- end wrapper -->
</body>
</html>